/**
 * Created by HP on 9/16/2020.
 */
export const FETCH_PEOPLE_REQUEST='FETCH_PEOPLE_REQUEST';
export const FETCH_PEOPLE_SUCCESS='FETCH_PEOPLE_SUCCESS';
export const FETCH_PEOPLE_FAILURE='FETCH_PEOPLE_FAILURE';